### ISSUE TITLE
IADLXPerformanceMonitoringServicesPtr->GetCurrentGPUMetrics causes high CPU usage

### ISSUE THREAD

**Issue by DevTechProfile** [GPUOpen-LibrariesAndSDKs/ADLX#11]
Function IADLXPerformanceMonitoringServicesPtr->GetCurrentGPUMetrics causes relatively high CPU usage, see screenshot below. The runtime is about 25ms per call. 

GPU: RX 7900 XTX
Driver: 23.9.1
Windows 11 Pro 22H2

![image](https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/assets/30285858/e11ca6bc-325e-4ddd-a312-4b08c262ea2c)

**Comment by ericjunwei** [comment]
If you'd like to continuously get the metrics data, please use GetGPUMetricsHistory() and set startMs and stopMs to 0.

**Comment by ericjunwei** [comment]
[void ShowHistoricalGPUMetrics(IADLXPerformanceMonitoringServicesPtr perfMonitoringServices, IADLXGPUPtr oneGPU)](https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/blob/main/Samples/CPP/PerformanceMonitoring/PerfGPUMetrics/mainPerfGPUMetrics.cpp#L45)

**Comment by DevTechProfile** [comment]
I have a question. What is best practise for using these API functions? Assuming I have a 1s polling rate in my app, what is the best strategy?

Is start and stop tracking supposed to to be called on every update trigger (1s polling rate) or just globally when initializing the app and stop on exit/shutdown? 

Did I understand correctly that there must be n milliseconds between perfMonitoringService->StartPerformanceMetricsTracking and perfMonitoringService->GetGPUMetricsHistory in order to get valid data for given interval?

**Comment by ericjunwei** [comment]
> I have a question. What is best practice for using these API functions? Assuming I have a 1s polling rate in my app, what is the best strategy?
> 
> Is start and stop tracking supposed to to be called on every update trigger (1s polling rate) or just globally when initializing the app and stop on exit/shutdown? In the latter case, the CPU overhead is unfortunately still very high.
> 
> Did I understand correctly that there must be n milliseconds between perfMonitoringService->StartPerformanceMetricsTracking and perfMonitoringService->GetGPUMetricsHistory in order to get valid data for given interval?
 Just globally when initializing the app and stop on exit/shutdown?

**Comment by DevTechProfile** [comment]
So you only call StartPerformanceMetricsTracking once on app start and StopPerformanceMetricsTracking only once too on app close? 

I've tried that and the CPU overhead is still present.

**Comment by DevTechProfile** [comment]
> Edit: Doing the polling this way, the performance is fine. That's strange, but it is what it is. Will have to figure out what the issue could be when calling GetGPUMetricsHistory from my app.

I was confusing Terminal and PerfGPUMetrics.exe in the Task Manager. There is definitely a significant CPU overhead, even when using  perfMonitoringServices->GetGPUMetricsHistory. I am afraid, you guys at AMD will have to improve this @ericjunwei.

**Comment by ericjunwei** [comment]
@DevTechProfile Please have a try with latest driver. https://www.amd.com/en/support

**Comment by DevTechProfile** [comment]
Thanks! Will check the driver.

**Comment by RodroG-85** [comment]
> @DevTechProfile Please have a try with latest driver. https://www.amd.com/en/support

I tried the latest _CapFrameX_ tool beta build and the latest Adrenalin driver (23.12.1), and the app's [higher-than-normal CPU usage issue](https://github.com/CXWorld/CapFrameX/issues/255) on idle/desktop conditions using an Intel 12th Gen + RDNA3 platform is finally fixed.

Thank you very much @ericjunwei, and @DevTechProfile

**Comment by RodroG-85** [comment]
Hello. The issue is back using the latest 24.1.1 Adrenalin driver.

**Comment by ericjunwei** [comment]
Are you using the RDNA3 ASIC?

**Comment by RodroG-85** [comment]
Hello @ericjunwei. I'm using an AMD Radeon 7900 XTX (Reference model, stock clocks).

**Comment by ericjunwei** [comment]
We cannot reproduce your issue. Do you use https://www.amd.com/en/support/graphics/amd-radeon-rx-7000-series/amd-radeon-rx-7900-series/amd-radeon-rx-7900xtx driver? Can you share the link you use?

**Comment by RodroG-85** [comment]
Hello @ericjunwei

I downloaded the latest driver from here:
https://www.amd.com/en/support/graphics/amd-radeon-rx-7000-series/amd-radeon-rx-7900-series/amd-radeon-rx-7900xtx

So, it's the same link and official source.

GPU: RX 7900 XTX
CPU: Intel 12th Gen i9-12900K
Driver: 24.1.1
Windows 11 Pro 23H1

The issue occurs with the CapFrameX v1.7.2 tool (release/latest build), which uses/integrates ADLX API functions. This program shows continuous CPU usage fluctuations from 0.1 to 0.3% on idle/desktop conditions that didn't occur before the program got RDNA3 support and integrated ADLX API.

[As reported in this thread](https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/issues/11#issuecomment-1848922013), this was fixed using the prior CapFrameX tool beta build and the Adrenalin driver v23.12.1. So, it can be the new Adrenalin driver version or the latest CapFrameX v1.7.2 causing this again.

@DevTechProfile, please, could you look into this too?

**Comment by DevTechProfile** [comment]
From my side using RX 7900 XT with latest driver everything is fine. 

![image](https://github.com/GPUOpen-LibrariesAndSDKs/ADLX/assets/30285858/1633e715-1999-4996-aa4d-676f827db2aa)

**Comment by RodroG-85** [comment]
Thank you for your feedback, @DevTechProfile 

I will check using your latest CapFrameX 1.7.3 beta build and let you know my results.

Best regards
