### ISSUE TITLE
Request: Please add ADL_Display_DitherState

### ISSUE THREAD

**Issue by lextra2** [GPUOpen-LibrariesAndSDKs/ADLX#15]
Please add back [ADL_Display_DitherState](https://gpuopen-librariesandsdks.github.io/adl/group__DISPLAYAPI.html#ga7603ce12ff0990ef1a393d3013cc4550) so users can change or disable the [dithering](https://gpuopen-librariesandsdks.github.io/adl/group__define__dither__states.html), since temporal dithering can cause eyestrain.

**Comment by andrewd38** [comment]
@lextra2 the link you supplied is actually from the 'Display Library' and not an earlier version of of ADLX. The display library (with [dithering functionality](https://github.com/GPUOpen-LibrariesAndSDKs/display-library/blob/29beb5a1217ab5805c5032284fdcdc56418bce36/include/adl_defines.h#L1013)) is available [here](https://github.com/GPUOpen-LibrariesAndSDKs/display-library)

**Comment by lextra2** [comment]
> @lextra2 the link you supplied is actually from the 'Display Library' and not an earlier version of of ADLX. The display library (with [dithering functionality](https://github.com/GPUOpen-LibrariesAndSDKs/display-library/blob/29beb5a1217ab5805c5032284fdcdc56418bce36/include/adl_defines.h#L1013)) is available [here](https://github.com/GPUOpen-LibrariesAndSDKs/display-library)

Thank you very much for those links!
