### ISSUE TITLE
Who is supposed to distribute the adlx dlls?

### ISSUE THREAD

**Issue by PeterTh** [GPUOpen-LibrariesAndSDKs/ADLX#4]
My assumption was that these would be distributed with the driver, but that doesn't appear to be the case.

I can make my ADLX program work by manually getting `amdadlx64.dll` from https://download.amd.com/dir/bin/amdadlx64.dll/, but I doubt this is the intended path.

Please clarify how this is supposed to work.

**Comment by ericjunwei** [comment]
adlx dll would be distributed with the driver.
