### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by sergioberg** [GPUOpen-LibrariesAndSDKs/ADLX#5]
My application is published on Steam. There is no problem with ADL, but when I try use ADLX there is issue:

![1](https://user-images.githubusercontent.com/12216723/213881914-184057e9-46f0-4daf-9585-34432ba17b80.PNG)

The Steam overlay (GameOverlayRenderer64.dll) interferes with ADLX and significantly increases CPU overhead when called to update metrics (GetCurrentGPUMetrics).
Disabling the overlay for my app in the Steam library settings does not make any difference (The same thing happens)

**Comment by ericjunwei** [comment]
@sergioberg , do you use GetCurrentXXXMetrics() method? It takes some time and is suitable for a single acquisition. For continuous collection, it is recommended to use GetXXXMetricsHistory()
